#!/usr/bin/python
"""
Outputs data formatted according to the 2010 data into csv 
Usage: field_visualizer <path_to_file>
path is relative to local directory
"""

import matplotlib.pyplot as plt
import numpy
import sys

def plot_count(fp):
	data = [int(l) for l in fp]

	counts = {}
	for point in data:
		if point in counts:
			counts[point] += 1
		else:
			counts[point] = 1
	
	print "Number of distinct points: ", len(counts.keys())	
	print "Mean", numpy.mean(data)
	print "Median", numpy.median(data)
	print "Max", numpy.max(data)
	print "Min", numpy.min(data)
	print "Standard deviation: ", numpy.std(data)

	print "    Field    :    Count  			   "
	print "----------------------------------------"
	for k, v in counts.items():
		print "   %d    :     %d    " % (k, v) 

	plt.hist(data, 10)
	plt.show()

def main(argv):
	if len(argv) < 2:
		print "Usage: field_visualizer <csv_name>"

	print "Visualizes a single field's distribution via histogram over a given dataset."

	fp = open(argv[1], 'r')
	plot_count(fp)
	fp.close()

if __name__ == "__main__":
	main(sys.argv)
